### ISSUE TITLE
Win 10 Tag Subject lost in NC?

### ISSUE THREAD

**Issue by BenBenna** [gino0631/nextcloud-metadata#57]
I have tagged a file in win10 (German Version) with "Titel" + "Betreff"
Point of interest: Titel + Betreff
![Metadata Win10](https://user-images.githubusercontent.com/14091725/73613546-1896dc00-45f7-11ea-9e53-dd9b4dc9975b.PNG)

this file carries the newlyy added tags over to f.ex. IrfanView (German Version)
Point of interest: XPTitle + XPSubject
![Metadata Irfan](https://user-images.githubusercontent.com/14091725/73613560-5267e280-45f7-11ea-916a-10233ec5d6cf.PNG)

in NC Metadata it looks  like this
Point of interest: Title: + Description
![Metadata Nextcloud NC](https://user-images.githubusercontent.com/14091725/73613567-63185880-45f7-11ea-8a35-9d14131b7c60.PNG)

Titel and description are (unfortunately) identical.
Can this be rectified?
It's a shame - but I'm not a programmer. Where I can help - i will. I would prefer a small financial support, but i have no Paypal-account. So i need a bank-account no. 

Thank you
Ben

**Comment by gino0631** [comment]
This is because Windows writes Title property to both `XMP:Description` and `XMP:Title`, and Subject to a proprietary `EXIF:XPSubject`, as discussed [here](https://exiftool.org/forum/index.php?topic=6591.0).

This behaviour creates problems for other software as well, [Adobe Lightroom for example](https://community.adobe.com/t5/lightroom-classic/can-t-edit-tag-quot-subject-quot-in-adobe-lightroom/td-p/9219323?page=1).

Was the expectation to see "Win Betreff" in the Description field?

**Comment by BenBenna** [comment]
Yes, it was
