### ISSUE TITLE
Can you make this work in photo app sidebar?

### ISSUE THREAD

**Issue by thve25** [gino0631/nextcloud-metadata#70]
I really like this plugin!
It would be even better if this plugin would also show up in the sidebar in the photos app.

Is that possible?

thanks

**Comment by gino0631** [comment]
@thve25 thank you for the positive feedback. I really don't know if the Photos app support this kind of integration. Most probably it would be necessary to move to the new Vue API, but it's just a guess - further analysis is necessary to determine what can be done.

**Comment by ollioddi** [comment]
Actually thought this was a bug, but i understand it's not. Since the release of the revamped Photos app and Nextcloud Hub 3, this would be a really nice improvement. I mainly intend to use the Photo addon to view metadata.

The Photos app already has the sidebar, but the metadata tab is missing.

I also use the OpenProject extension, which is shown in the Photo app sidebar. Is it a configuration issue that prevents the Metadata tab from showing?

**Comment by gino0631** [comment]
@ollioddi that's probably because of the newer implementation using Vue - the app is not yet compatible with that. Thanks for the ping, I'll take a look.

**Comment by ollioddi** [comment]
@gino0631 very much appreciated. Hope that it's possible someday!

**Comment by gino0631** [comment]
Closing, as this got implemented as a byproduct of compatibility with NC 28 (see #105).
